- src/backend.rs
- src/config.rs
- src/frontend.rs
- src/icmp.rs
- src/icmp/config.rs
- src/icmp/net.rs
- src/icmp/tracer.rs
- src/main.rs
> Add support for tracing using the `udp` protocol (WIP)

- README.md
- src/backend.rs
- src/config.rs
- src/frontend.rs
- src/main.rs
> Feat show hop count

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/main.rs
- src/report.rs
> Feat report table

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/dns.rs
- src/frontend.rs
- src/main.rs
- src/report.rs
> Feat dns non blocking

- README.md
- src/config.rs
- src/dns.rs
- src/frontend.rs
- src/main.rs
> Lookup AS data

- src/tracing/error.rs
- src/tracing/net.rs
> `TCP` checksum not being set

- src/backend.rs
- src/tracing/tracer.rs
> Fix tearing

- src/backend.rs
- src/tracing.rs
- src/tracing/tracer.rs
> Feat remove circular buffer

- README.md
- src/dns.rs
- src/frontend.rs
> Flush DNS cache

- src/tracing/tracer.rs
> fix: `largest_ttl` set incorrectly when `first-ttl` and `max-ttl` specified

- README.md
- src/backend.rs
- src/config.rs
- src/frontend.rs
- src/main.rs
> Feat configure max samples

- src/caps.rs
> fix: incorrect conditional complication for `Windows` in `caps.rs`

- CHANGELOG.md
- README.md
- src/config.rs
- src/frontend.rs
- src/main.rs
> Feat multiball

- src/dns.rs
- src/frontend.rs
- src/main.rs
> Allow toggling ASN in Tui

- src/tracing/tracer.rs
> fix(tracer): incorrect handling of `DestinationUnreachable` packets for `udp` tracing

- src/main.rs
> feat: show a better error message for a failed DNS lookup

- Cargo.lock
- Cargo.toml
- src/tracing/net.rs
> Feat discover local addr v2

- src/tracing/net.rs
> fix(net): UDP checksum was not being set

- src/tracing/net.rs
> Feat use socket for udp tracing

- src/config.rs
- src/main.rs
- src/tracing/error.rs
- src/tracing/net.rs
> feat: added `source_address` cli option to specify the desired source IP address (#162)

- src/config.rs
- src/main.rs
> feat: rename cli flag `tui-max-addresses-per-hop` as `tui-max-addrs`

- src/config.rs
- src/main.rs
> Feat explicit cli flag order

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/tracing/error.rs
- src/tracing/net.rs
> Feat net interface

- src/config.rs
- src/frontend.rs
- src/main.rs
- src/tracing.rs
- src/tracing/config.rs
- src/tracing/error.rs
- src/tracing/net.rs
- src/tracing/tracer.rs
- src/tracing/types.rs
> Allow fixing either source or destination port for UDP and TCP tracing

- src/frontend.rs
> feat(ui): add Ctrl-C as an alternative keyboard input to quit the app

- src/main.rs
- src/report.rs
> fix(report): tracer failures not being shown for reports (#183)

- Cargo.lock
- Cargo.toml
- src/config.rs
> Feat protocol shortcut

- CHANGELOG.md
- README.md
- src/config.rs
- src/tracing/net/channel.rs
- src/tracing/net/ipv4.rs
- src/tracing/net/ipv6.rs
> feat(channel): added support for `TCP` over `IPv6`

- .github/workflows/ci.yml
- README.md
> Build ci on macos

- CHANGELOG.md
- README.md
- src/frontend.rs
> feat(tui): added chart display of all hops

- CHANGELOG.md
- src/backend.rs
- src/frontend.rs
> Feat tui show round hops

- src/tracing/net/channel.rs
- src/tracing/net/ipv4.rs
- src/tracing/net/platform.rs
- src/tracing/packet/ipv4.rs
> Fix ipv4 flags and fragment offset

- src/config.rs
- src/frontend.rs
- src/main.rs
- src/tracing.rs
- src/tracing/config.rs
- src/tracing/net/channel.rs
- src/tracing/net/ipv4.rs
> feat: implement the dublin multipath routing strategy for IPv4/UDP

- Cargo.lock
- Cargo.toml
> Revert crossterm and tui

- src/tracing/tracer.rs
> fix: incorrect trace for udp and tcp equal cost multi-path routing

- Cargo.toml
- src/config.rs
- src/frontend.rs
- src/tracing/net/channel.rs
- src/tracing/net/ipv6.rs
- src/tracing/tracer.rs
Found via `typos --format brief`
> doc: fix typos

- Cargo.lock
- Cargo.toml
- Dockerfile
> Build docker alpine and update crossterm

- .github/workflows/release.yml
- Cargo.toml
Created RPM package using github actions
Hence, upon each new release the package gets generated accordingly
Closes #95
> RPM packaging #95

- src/tracing/net/platform/windows.rs
> feat: add support for Windows (#98)

- CHANGELOG.md
- src/tracing.rs
- src/tracing/config.rs
- src/tracing/constants.rs
- src/tracing/tracer.rs
> Fix tracer panic initial sequence

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/frontend.rs
- src/main.rs
> Support custom keyboard bindings

- .github/workflows/release.yml
> fix: generate zip archive for windows releases to support winget

- CHANGELOG.md
- README.md
- src/config.rs
- src/dns.rs
- src/frontend.rs
- src/main.rs
> feat: lookup and display ASN for unresolved addresses

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- README.md
> Reinstate musl release builds

- Cargo.lock
- Cargo.toml
- src/caps.rs
- src/main.rs
> Ensure administrator privileges on Windows

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
> Add support for shell completions

- CHANGELOG.md
- README.md
- src/config.rs
> Fix: Do not require passing targets for certain command line

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- deny.toml
- src/config.rs
- src/frontend.rs
- src/geoip.rs
- src/main.rs
- trippy-config-sample.toml
> Add support for GeoIp lookup and display

- CHANGELOG.md
- src/frontend.rs
> Fix double tap windows

- CHANGELOG.md
- src/config.rs
> fix: error message command line names should be in kebab-case (#516)

- README.md
> Mark FreeBSD as tested and add pkg install (#214)

- README.md
> doc: update README.md to add nix package

- CHANGELOG.md
- src/tracing/error.rs
- src/tracing/net/ipv4.rs
- src/tracing/net/ipv6.rs
- src/tracing/net/platform/unix.rs
- src/tracing/net/platform/windows.rs
- src/tracing/net/socket.rs
> feat: add custom IoError

- Cargo.lock
- Cargo.toml
- src/frontend.rs
> Migrate from `tui` to `ratatui`

- .github/workflows/release.yml
> build: add a `musl` `deb` package build to release (#568)

- CHANGELOG.md
- src/report.rs
> Add `IPs` field to all reports

- src/tracing/net/channel.rs
> fix(net): only create the needed icmp or udp sending socket

- src/tracing/net/platform/unix.rs
> Fix: handle `EINTR` in calls to `select`

- README.md
> doc: add FAQ for configuring Windows Defender firewall to `README.md`

- src/tracing/packet/ipv4.rs
> fix: changed `Ipv4Packet::payload()` to not be based on total_length which is platform dependant

- src/tracing/net/ipv4.rs
- src/tracing/net/ipv6.rs
> fix(net): ensure the actual and expected original datagram protocol match or discard the packet (#745)

- README.md
- src/backend.rs
- src/config.rs
- src/config/cmd.rs
- src/config/constants.rs
- src/config/file.rs
- src/frontend/render/header.rs
- src/main.rs
- src/platform.rs
- src/tracing.rs
- src/tracing/config.rs
- src/tracing/net.rs
- src/tracing/net/channel.rs
- src/tracing/net/common.rs
- src/tracing/net/ipv4.rs
- src/tracing/net/ipv6.rs
- src/tracing/net/platform/unix.rs
- src/tracing/net/platform/windows.rs
- src/tracing/net/socket.rs
- trippy-config-sample.toml
> Add Support for `--unprivileged` mode (MacOS only)

- src/config.rs
- src/config/cmd.rs
- src/config/constants.rs
- src/config/file.rs
- src/frontend/render/settings.rs
- src/main.rs
- trippy-config-sample.toml
> Add `dns_resolve_all` flag to trace to all resolved ips (#743)

- src/backend.rs
- src/backend/flows.rs
- src/backend/trace.rs
Closes https://github.com/fujiapple852/trippy/issues/768
> Record tracing flows

- src/backend/trace.rs
- src/frontend/render/body.rs
- src/frontend/render/chart.rs
- src/frontend/render/header.rs
- src/frontend/render/table.rs
- src/frontend/render/world.rs
- src/frontend/tui_app.rs
- src/report.rs
Closes https://github.com/fujiapple852/trippy/issues/760
> Segregate traces by flow

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/report.rs
- trippy-config-sample.toml
> Add dot report mode

- README.md
- src/config.rs
- src/config/cmd.rs
> feat: add `--print-config-template` flag to output template config file

- .github/workflows/release.yml
> build: add `aarch64-apple-darwin` release target (#801)

- .github/workflows/release.yml
> Support `armv7` release builds

- .github/workflows/release.yml
> Build add targets

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/config/binding.rs
- src/config/constants.rs
- src/config/file.rs
- src/config/theme.rs
- src/dns/lazy_resolver.rs
- src/main.rs
- src/platform.rs
- src/tracing/config.rs
- trippy-config-sample.toml
> Added config tests

- src/frontend.rs
> feat(tui): add panic handler to reset terminal

- Cargo.lock
- Cargo.toml
- snap/snapcraft.yaml
> 0.9.0 release

- src/frontend/tui_app.rs
> fix(tui): `expand-hosts-max` command panics if no addresses for any hop (#892)

- src/report.rs
- src/tracing/config.rs
- src/tracing/tracer.rs
- src/tracing/types.rs
> fix(tracer): off-by-one bug in `Tracer::finished` (#906)

- Cargo.lock
- Cargo.toml
- src/geoip.rs
> feat(geoip): add support for IpInfo `mmdb` files (#862)

- tests/sim/network.rs
- tests/sim/tests.rs
- tests/sim/tracer.rs
adds a delay between tests to allow inflight traffic to complete adds a retry mechaism to try each test up to 3 times cancel all pending network packet sends when network is shutdown
> test: improve robustness of tun simulator tests

- .github/workflows/ci.yml
> build: add cargo cross build ci job for `netbsd` and `freebsd`

- src/frontend/columns.rs
- src/frontend/render/table.rs
> feat(tui): improve column width layout logic

- src/config.rs
> feat: validate protocol against ecmp strategy (#848)

- README.md
- trippy-config-sample.toml
> Document columns and add jitter to config file template

- .github/ISSUE_TEMPLATE/bug_report.md
Add a bit more info to hopefully help users understand what is being requested of them
> doc: add more comments to clarify request for console

- Cargo.lock
- Cargo.toml
- deny.toml
- src/config/file.rs
> Fix config encoding

- src/backend/trace.rs
- src/config/columns.rs
- src/frontend/columns.rs
- src/frontend/render/table.rs
> feat: add src and dest port custom columns (#974)

- src/backend/trace.rs
- src/config/columns.rs
- src/frontend/columns.rs
- src/frontend/render/table.rs
> feat: add sequence number custom column (#976)

- src/config.rs
- src/config/constants.rs
> fix(config): incorrect minimum packet size for ipv6 (#985)

- .github/workflows/pr_agent.yml
enhancement
___
- Enabled automation features in the PR agent configuration to improve PR handling:
- Automatic review, description, and improvement functionalities are now active.
- The requirement for estimating effort to review has been disabled.
- Publishing of labels in PR descriptions has been turned off.
___
<tr>
<td>
<details>
<summary><strong>pr_agent.yml</strong><dd><code>Enhance PR Agent Configuration for Automation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/pr_agent.yml
<li>Enabled automatic review, description, and improvement by the PR …
> build: update `pr-agent` configuration

- src/tracing/net/ipv6.rs
enhancement, tests
___
- Introduced minimum packet size checks for ICMP and UDP probes in IPv6, enhancing packet validation.
- Added a wide range of unit tests for IPv6 functionality, covering probe dispatching and receiving, handling of different ICMP types, and packet size validation.
- Utilized mutex locking in tests to ensure thread safety.
___
<tr>
<td>
<details>
<summary><strong>ipv6.rs</strong><dd><code>Add Minimum Packet Size Checks and Constants</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/tracing/net/ipv6.rs
<li>Added constants for minimum packet sizes for ICMP and UDP …
> add ipv6 unit tests

- tests/resources/simulation/ipv4_udp_dublin_fixed_both.yaml
- tests/sim/tests.rs
tests, enhancement
___
- Added a new test case for IPv4/UDP Dublin simulations with fixed source and destination ports to enhance the test suite.
- Introduced a new simulation configuration file `ipv4_udp_dublin_fixed_both.yaml` detailing the simulation steps, including the multipath strategy (Dublin), and expected responses at different TTLs.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>tests.rs</strong><dd><code>Add IPv4/UDP Dublin Simulation Test Case</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
tests/sim/tests.rs
<li>Added a new test case …
> test(sim): add ipv4/udp dublin tests

- README.md
documentation, enhancement
___
- Introduced a new command-line option `-F, --addr-family` to specify the address family with support for IPv4 and IPv6 configurations.
- Added a new `--tui-custom-columns` option allowing customization of columns in the TUI hops table.
- Enhanced the description for the `--geoip-mmdb-file` option to include support for IPinfo GeoIp mmdb files.
- Corrected grammatical errors and clarified existing command descriptions for better readability.
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Documentation Improvements and New Features in Command Reference</code></dd></summary>
<hr>
README.md
<li>Corrected …
> doc: updated Command Reference section of README.md

- Cargo.lock
- Cargo.toml
- README.md
- snap/snapcraft.yaml
enhancement, documentation
___
- Updated the project version to `0.10.0` in `Cargo.toml` and `snapcraft.yaml`.
- Enhanced the `README.md` and `snapcraft.yaml` with new Tui interface features: jitter in per hop stats and customizable column order and visibility.
- Updated the `README.md` with new version `0.10.0` details, including updated badge, versions table, and binary asset download links.
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update Package Version to 0.10.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Release prep 0.10.0

- CHANGELOG.md
- README.md
documentation
___
- Added documentation for installing the project via Ubuntu PPA, including a new section in `README.md` with a version badge and installation commands.
- Updated `CHANGELOG.md` to include the addition of Ubuntu PPA package support.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Update CHANGELOG for Ubuntu PPA Package Addition</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
CHANGELOG.md
<li>Added a note about the Ubuntu PPA package addition in the Unreleased <br>section.
</details>
</td>
<td><a href="https://github.com/fujiapple852/trippy/pull/1087/files#diff-06572a96a58d …
> Doc readme add PPA package

- .devcontainer/devcontainer.json
enhancement
___
- Introduced a `devcontainer.json` for GitHub Codespaces to streamline development setup.
- Utilizes the universal base image from Microsoft and includes Rust development features.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>devcontainer.json</strong><dd><code>Setup GitHub Codespaces Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.devcontainer/devcontainer.json
<li>Added a new <code>devcontainer.json</code> file to configure development <br>environments in GitHub Codespaces.<br> <li> Configured the …
> build: add codespaces devcontainer.json

- CHANGELOG.md
- README.md
- src/backend/trace.rs
- src/config/columns.rs
- src/frontend/columns.rs
- src/frontend/render/table.rs
- trippy-config-sample.toml
> New column: last icmp packet type

- Cargo.toml
- crates/trippy-core/src/probe.rs
- crates/trippy-core/src/strategy.rs
> refactor(core): introduce `StrategyResponse` and `StrategyResponseSeq`

- crates/trippy-core/src/state.rs
> fix(core): calculate target hop from maximum hop per round (#1226)

- crates/trippy-core/src/error.rs
- crates/trippy-core/src/net/common.rs
- crates/trippy-core/src/strategy.rs
> fix(core): do not conflate AddressInUse and AddrNotAvailable errors

- crates/trippy-core/src/error.rs
- crates/trippy-core/src/net/common.rs
- crates/trippy-core/src/net/ipv4.rs
- crates/trippy-core/src/net/platform/unix.rs
- crates/trippy-core/src/net/platform/windows.rs
- crates/trippy-core/src/probe.rs
- crates/trippy-core/src/state.rs
- crates/trippy-core/src/strategy.rs
- crates/trippy-tui/src/config/columns.rs
- crates/trippy-tui/src/frontend/columns.rs
- crates/trippy-tui/src/frontend/render/header.rs
- crates/trippy-tui/src/frontend/render/table.rs
- trippy-config-sample.toml
> Transient error handling for IPv4 (macOS, Linux & Windows)

- CHANGELOG.md
- crates/trippy-tui/src/frontend.rs
- crates/trippy-tui/src/frontend/render/help.rs
- crates/trippy-tui/src/frontend/render/settings.rs
> Revamp the help dialog

- crates/trippy-tui/src/frontend/render/settings.rs
> fix(tui): add missing `tui-icmp-extension-mode` to settings dialog

- CHANGELOG.md
- crates/trippy-dns/src/lazy_resolver.rs
- crates/trippy-dns/src/lib.rs
- crates/trippy-dns/src/resolver.rs
- crates/trippy-tui/src/frontend/render/table.rs
> fix(dns): reverse dns enqueued multiple times wen ttl expires (#1290)

- debian/release.sh
- debian/rules
> build: update debian `release.sh` for multiple series

- CHANGELOG.md
- crates/trippy-dns/src/resolver.rs
- crates/trippy-tui/src/frontend/render/header.rs
> Only show hostnames if different from IPs

- crates/trippy-tui/src/frontend/render/world.rs
note that bug was introduced in #1366 which has not been released
> fix(tui): off-by-one error for privacy ttl on the world map

- crates/trippy-dns/src/lazy_resolver.rs
> fix(dns): IP strategy option not respected for dns resolve method `resolv` (#1461)

- crates/trippy-core/src/flows.rs
- crates/trippy-core/src/net/channel.rs
- crates/trippy-core/src/net/ipv4.rs
- crates/trippy-core/src/net/ipv6.rs
- crates/trippy-core/src/net/platform/unix.rs
- crates/trippy-core/src/net/platform/windows.rs
- crates/trippy-core/src/state.rs
- crates/trippy-core/src/strategy.rs
- crates/trippy-core/src/tracer.rs
- crates/trippy-tui/src/app.rs
> Feat reduce tracing

- crates/trippy-tui/src/config.rs
> feat(tui): remove address family downgrade for dublin ECMP strategy (#1476)

- crates/trippy-core/src/net/platform/windows.rs
> fix(core): missing null pointer check in `AdaptersIter` in `windows.rs`

- crates/trippy-tui/src/frontend/render/settings.rs
> fix(tui): items missing from settings dialog (#1541)

- CHANGELOG.md
- Cargo.toml
- Dockerfile
- crates/trippy-core/src/net/platform/windows.rs
- examples/hello-world/Cargo.toml
- examples/toy-traceroute/Cargo.toml
- ubuntu-ppa/Dockerfile
- ubuntu-ppa/control
- ubuntu-ppa/release.sh
- ubuntu-ppa/rules
> bump msrv to 1.82

- ubuntu-ppa/README.md
- ubuntu-ppa/release.sh
> build: update ubuntu ppa release script
