README.md
I've just packaged and merged `trippy` into the main branch of pkgsrc.
This means the application is now available for NetBSD users. It builds and runs fine on NetBSD.
https://mail-index.netbsd.org/pkgsrc-changes/2022/05/01/msg253439.html
Regards
=> Trippy now available on NetBSD

src/frontend.rs
=> fix: `DisableMouseCapture` was being invoked without a prior `EnableMouseCapture`

src/lib.rs
=> doc: Use project README.md as documentation for the library crate on `docs.rs` (#128)

src/dns.rs
=> fix(dns): do not show `fqdn` for reverse DNS queries from `TrustDns` resolver

src/main.rs
=> fix: filter for Ipv4 addresses when resolving hostnames

src/config.rs, src/frontend.rs, src/main.rs, src/report.rs, src/tracing.rs, src/tracing/config.rs, src/tracing/net.rs, src/tracing/tracer.rs
=> Feat show source address

src/config.rs, src/main.rs, src/tracing/net.rs, src/tracing/types.rs
=> feat: added `--tos` (`-Q`) flag to set the `TOS` (aka `DSCP`+`ECN`) flag for `TCP` and `UDP` tracing

src/backend.rs, src/report.rs
=> fix(report): setting `--report-cycles` to `1` returns no traces (#189)

.github/workflows/ci.yml, Dockerfile, src/tracing/packet/buffer.rs, src/tracing/packet/icmpv4.rs, src/tracing/packet/icmpv6.rs, src/tracing/packet/ipv4.rs, src/tracing/packet/ipv6.rs, src/tracing/packet/tcp.rs, src/tracing/packet/udp.rs
…` methods using const generics
=> refactor: simplify `Buffer::get_bytes_xxx` and `Buffer::set_bytes_xxx`

.github/workflows/release.yml
=>  Generate deb package on release #94 

src/backend.rs, src/main.rs, src/tracing/config.rs, src/tracing/net/channel.rs
=> refactor: move `TracerChannel` creation inside the `run_backend()`

src/tracing/net/ipv6.rs
Removed to align with the Windows implementation.  Tested on MacOS and Linux for ICMP and UDP.
=> fix: remove redundant bind call for ICMP and UDP tracing over IPv6

CHANGELOG.md, src/tracing/net/channel.rs
=> fix: `tcp` tracing may ignore some incoming `icmp` responses (#407)

.github/workflows/release.yml
This reverts commit 0309c75b58abcfac85638dacc690d3647703c479.
=> Revert "fix: generate windows zip archive on trip.exe directly"

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config.rs, trippy-config-sample.toml
=> Add support for a config file

Cargo.lock, Cargo.toml, README.md, src/config.rs, trippy-config-sample.toml
`~/Library/Application Support` is an utterly inconvenient location for macOS users. Most CLI tools follow the `XDG conventions` on macOS as well. Replace the `dirs` crate with the `etcetera` crate to support it on macOS as well. Config locations for other platforms are unaffected.
Closes #539.
Closes #540.
Closes #541.
=> feat!: use XDG conventions on macOS too

CHANGELOG.md, src/dns.rs, src/frontend/render/header.rs, src/frontend/render/table.rs, src/report.rs
=> Add blocking reverse DNS lookup

src/dns.rs
Fixes bug introduced by #596 on master (was never released in any version)
=> fix(dns): resolver queue processor blocking lazy lookup

src/tracing/net/ipv4.rs
=> fix(net): remove redundant calls to `TimeExceededPacket::new_view()` in `ipv4.rs`

README.md, src/config/binding.rs, src/config/file.rs, src/frontend.rs, src/frontend/binding.rs, src/frontend/render/help.rs, src/frontend/render/settings.rs, trippy-config-sample.toml
=> Feat help alt key binding

README.md, src/config.rs, src/config/cmd.rs
=> improve bool flags (#708)

src/backend.rs, src/tracing.rs, src/tracing/net.rs, src/tracing/net/channel.rs, src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/net/platform/unix.rs, src/tracing/net/platform/windows.rs, src/tracing/net/socket.rs, src/tracing/net/source.rs
Make the net code generic of `S: Socket` so we can mock out the socket impl for better testing
=> refactor: Generic socket

trippy-config-sample.toml
Found via `typos --hidden --format brief`
=> Fix typos in sample config

src/config.rs, src/config/cmd.rs, src/tracing/net/channel.rs, src/tracing/net/ipv6.rs, trippy-config-sample.toml
=> feat(net): add `Paris` ECMP strategy support for `Ipv6/UDP` (#749)

src/config.rs, src/config/cmd.rs, src/config/constants.rs, src/config/file.rs, src/frontend/config.rs, src/frontend/render/settings.rs, src/frontend/render/table.rs, src/frontend/render/world.rs, src/main.rs, trippy-config-sample.toml
=> Add Privacy Mask

src/config.rs, src/config/cmd.rs
The following tests for the mentioned use case:
1) Change protocol in the config file to non default tcp or udp.
2) Run trippy with shortcut --icmp
Results:
Config: protocol=icmp(v4, unprivileged) as-info=n/a details=off max-hosts=auto 
This passed the basic use case please post comments if others should be run
Closes #649
=> Add icmp argument to allow shortcut for base protocol

Cargo.lock, Cargo.toml, src/backend/trace.rs, src/config.rs, src/config/cmd.rs, src/config/file.rs, src/main.rs, src/tracing.rs, src/tracing/config.rs, src/tracing/net.rs, src/tracing/net/channel.rs, src/tracing/net/extension.rs, src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/packet.rs, src/tracing/packet/icmp_extension.rs, src/tracing/packet/icmpv4.rs, src/tracing/packet/icmpv6.rs, src/tracing/probe.rs, src/tracing/tracer.rs, trippy-config-sample.toml
Closes #751 
Closes #753 
Closes #807
=> Icmp Extensions v2

src/tracing/net/channel.rs, src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/net/platform/unix.rs, src/tracing/net/platform/windows.rs, src/tracing/net/socket.rs
Closes https://github.com/fujiapple852/trippy/issues/843
=> refactor(net): use exclusive `&mut` for socket operations (#843)

src/config.rs, src/config/cmd.rs, src/config/columns.rs, src/config/constants.rs, src/config/file.rs, src/frontend.rs, src/frontend/columns.rs, src/frontend/config.rs, src/frontend/render/settings.rs, src/frontend/render/table.rs, src/main.rs, trippy-config-sample.toml
Added:
Custom columns to TUI interface by either the configuration file or command line option
Calculation of column percentage with 40% constant percentage for hosts column.
Unit tests for TuiColumns and Columns classes 
cargo test frontend::columns
cargo test config::columns
Tests run:
cargo run -- -u --tui-custom-columns="" -m tui freebsd.org
cargo run -- -u -c ./trippy-config-sample.toml -m tui freebsd.org
cargo run -- -u --tui-custom-columns="" -c ./trippy-config-sample.toml -m tui freebsd.org
cargo run -- -u --tui-custom-columns="" -m tui freebsd.org
cargo run -- -u --tui-custom-columns="thobwd" -m tui freebsd.org
=> feat: Allow Custom Columns TUI

.github/workflows/ci.yml, src/tracing/net/platform/windows.rs
was previously removed in cbc2f31a931ef2eb9dd5ac48660c9ced14227355 but unclear why.
=> build: reinstate macos and windows clippy CI jobs

src/backend/trace.rs, src/config/columns.rs, src/frontend/columns.rs, src/frontend/render/table.rs, src/report/types.rs
Closes #39 (by @trkelly23)
The first of three PRs adding the 4 jitter columns to the backend and TUI + JSON:
Optional columns Jttr, Javg, Jmax & Jinta
1. The current jitter i.e. round-trip difference with the last round-trip ('Jttr')
2. The average jitter time for all probes at this hop ('Javg')
3. The best round-trip jitter time for all probes at this hop ('Jmax')
4. The smoothed jitter value for all probes at this hop ('Jint')
Testing by running with the optional jitter columns or specify JSON output.
```
cargo run -- -u --tui-custom-columns="THOLSRAVBWjgxi" freebsd.org
```
JSON output:
```
cargo run -- -u -m json freebsd.org  
```
=> feat: calculate and display jitter (#39)

src/config.rs, src/config/cmd.rs, src/config/constants.rs, src/config/file.rs, src/dns.rs, src/dns/lazy_resolver.rs, src/frontend/render/header.rs, src/main.rs, src/tracing.rs, src/tracing/config.rs, test_resources/completions_bash.txt, test_resources/completions_elvish.txt, test_resources/completions_fish.txt, test_resources/completions_powershell.txt, test_resources/completions_zsh.txt, test_resources/usage_long.txt, test_resources/usage_short.txt, trippy-config-sample.toml
=> feat: add support `dns-resolve-family` (#864)

Cargo.lock, Cargo.toml, src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/net/socket.rs, src/tracing/packet/icmpv4.rs, src/tracing/packet/icmpv6.rs
=> fix(net): tracer panic for ICMP TimeExceeded packets with code 1 (#979)

src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/probe.rs, src/tracing/tracer.rs
=> fix(net): filter unrelated ICMP responses for TCP and UDP (#981)

src/backend/trace.rs, src/tracing.rs, test_resources/backend/ipv4_3probes_3hops_completed.yaml, test_resources/backend/ipv4_3probes_3hops_mixed_multi.yaml, test_resources/backend/ipv4_4probes_0latency.yaml, test_resources/backend/ipv4_4probes_all_status.yaml
The PR includes tests for a single hop and 0 to n probes for various probe statuses.  
Note: I did not add mean & m2 to the equality test but plan to add them later.
During tests, it was found that low latency of .5 millis the Jinta value turned negative.  According to the RFC near zero should remain 0 because is minimal.  Added check jinta.max(0.5)
A couple of items to please review:
1) I made tracer & type(src/tracing.rs) public to integrate with tests.  Not completely kosher as some libs are private and public.
2)  I'm looking for a suggestion to add multiple hops to tests.  Can you please suggest it?
3) Are there other missing test cases besides multiple hops?
4) The location of the YAML files is under the backend folder.  I ran into multiple issues moving outside the src directory. …
=> test: add backend tracer tests

src/tracing/net/ipv4.rs, tests/resources/simulation/ipv4_udp_classic_unprivileged.yaml, tests/sim/simulation.rs, tests/sim/tests.rs, tests/sim/tracer.rs
bug_fix
___
- Updated UDP socket creation to use `new_udp_send_socket_ipv4(false)` for non-blocking mode, replacing the previous `new_udp_dgram_socket_ipv4` method.
- Modified unit tests to align with the new method of UDP socket creation, ensuring the correct behavior of non-blocking sockets.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ipv4.rs</strong><dd><code>Update UDP Socket Creation to Non-Blocking Mode</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/tracing/net/ipv4.rs
<li>Updated the method to create a UDP socket from <br><code>new_udp_dgram_socket_ipv4</code> to <code>new_udp_send_socket_ipv4</code> …
=> fix(net): create non-raw ipv4 socket with `new_udp_send_socket_ipv4(false)`

src/tracing/net/extension.rs, src/tracing/packet/buffer.rs, src/tracing/packet/checksum.rs, src/tracing/packet/error.rs, src/tracing/packet/icmpv4.rs, src/tracing/packet/icmpv6.rs, src/tracing/packet/ipv4.rs, src/tracing/packet/ipv6.rs, src/tracing/packet/tcp.rs, src/tracing/packet/udp.rs
Tests, Enhancement
___
- Added a variety of unit tests across different modules, focusing on buffer functionalities, checksum calculations, and error handling.
- Introduced tests for handling insufficient buffer sizes for packet creation across multiple protocols (ICMPv4, ICMPv6, IPv4, IPv6, TCP, UDP).
- Enhanced `PacketError` with `Eq` and `PartialEq` traits to facilitate better testing.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>extension.rs</strong><dd><code>Added Unit Tests for ICMP Extensions Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> add more unit tests

src/frontend/render/table.rs
Closes #1045 
Fix for bug 1045
Purpose:
Fixes a display issue for hops with "No Response" displaying "0.0" in the javg & jint columns.  The solution checks total_recv > 0 to use the value just like all the other columns do.
___
bug_fix
___
- Fixes a display issue where metrics like jitter and average were incorrectly shown for hops with no responses.
- Ensures that metrics are only displayed if there are received packets, improving the accuracy of the table display.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>table.rs</strong><dd><code>Fix Display of Jitter and Other Metrics for No Response Scenarios</code></dd></summary>
<hr>
src/frontend/render/table.rs …
=> fix(tui): Jitter display bug no response

src/tracing/net/platform.rs, src/tracing/net/source.rs
tests, enhancement
___
- Added `mockall::automock` to the `Platform` trait to facilitate mocking for tests.
- Introduced extensive testing for `SourceAddr::discover` method, covering default port discovery, fixed destination port, fixed both source and destination ports, and interface lookup scenarios.
- Implemented tests for `SourceAddr::validate` to ensure correct behavior for both IPv4 and IPv6 addresses, including handling of invalid addresses.
- Employed `MockPlatform` and `MockSocket` to mock external dependencies in the testing environment.
- Added a static mutex (`MTX`) to ensure thread safety across tests.
___
<tr>
<td>
<details> …
=> add source module tests

snap/snapcraft.yaml
Supports #1058
___
enhancement
___
- Added the `home` plug to the Snap configuration to enable reading the configuration file from `/home`.
- This change allows the application to access necessary files in the user's home directory, enhancing its functionality and user experience.
___
<tr>
<td>
<details>
<summary><strong>snapcraft.yaml</strong><dd><code>Add `home` plug to Snap configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
snap/snapcraft.yaml
<li>Added <code>home</code> plug to allow access to <code>/home</code> for reading …
=> fix: add snap plug `home` to allow accessing the configuration file from `/home`

src/frontend/render/table.rs, src/geoip.rs
enhancement
___
- Simplified the determination of a selected hop in the traceroute table rendering by using `is_some_and`.
- Improved the readability and efficiency of the GeoIP lookup cache access by using `cloned()` instead of `map(Clone::clone)`.
___
<tr>
<td>
<details>
<summary><strong>table.rs</strong><dd><code>Simplify Selected Hop Logic with `is_some_and`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/frontend/render/table.rs
<li>Simplified the logic to determine if a hop is selected using <br><code>is_some_and</code>.
</details>
</td>
<td><a …
=> chore: clippy lints for Rust 1.77.0

tests/resources/simulation/ipv4_icmp_wrap.yaml, tests/sim/network.rs, tests/sim/simulation.rs, tests/sim/tests.rs, tests/sim/tracer.rs
enhancement, tests
___
- Introduced a read timeout in network simulation to prevent lock starvation.
- Added new simulation parameters `rounds` and `initial_sequence` for detailed control.
- Included a new simulation test case `ipv4_icmp_wrap.yaml` to validate the wrap sequence handling.
- Enhanced error logging in simulation tests for better debugging.
- Configured tracer to support new simulation parameters, allowing for more flexible test scenarios.
___
<tr>
<td>
<details>
<summary><strong>network.rs</strong><dd><code>Enhance Network Simulator with Read Timeout and Error Handling</code></dd></summary>
<hr>
tests/sim/network.rs
<li>Introduced a constant …
=> Simulator improvements

snap/snapcraft.yaml
enhancement
___
- Enhanced the snap permissions by specifying `read: all` for the `home` interface in `snapcraft.yaml`. This allows the application to have read access to all user files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>snapcraft.yaml</strong><dd><code>Enhance Snap Permissions for Home Interface</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
snap/snapcraft.yaml
- Added `read: all` permission to the `home` interface.
</details>
</td>
<td><a href="https://github.com/fujiapple852/trippy/pull/1066/files#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5">+ …
=> build: use `read: all` for snap `home` interface

src/tracing/constants.rs, src/tracing/tracer.rs
Closes #1067
___
enhancement
___
- Reduced the `MAX_SEQUENCE_PER_ROUND` from 1024 to 512 in `src/tracing/constants.rs` to improve efficiency.
- Updated test cases in `src/tracing/tracer.rs` to align with the new max sequence per round value, ensuring consistency and correctness.
___
<tr>
<td>
<details>
<summary><strong>constants.rs</strong><dd><code>Reduce Max Sequence Per Round for Efficiency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/tracing/constants.rs
- Reduced `MAX_SEQUENCE_PER_ROUND` from 1024 to 512.
</details>
</td>
<td><a …
=> feat(net): reduce `MAX_SEQUENCE_PER_ROUND` from 1024 to 512 (#1067)

snap/snapcraft.yaml
enhancement
___
- Moved the `home` plug configuration from the `apps` section to the top-level `plugs` section in `snapcraft.yaml`.
- This change ensures that the `home` plug is correctly configured with `read: all` permissions, enhancing the application's access management.
___
<tr>
<td>
<details>
<summary><strong>snapcraft.yaml</strong><dd><code>Refactor Snap `home` Plug Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
snap/snapcraft.yaml
<li>Moved <code>home</code> plug configuration to the top-level <code>plugs</code> …
=> fix: move snap plug `home` configuration to top level `plugs`

src/frontend.rs, src/frontend/columns.rs, src/frontend/render/settings.rs, src/frontend/render/table.rs, src/frontend/tui_app.rs
Closes #1026
___
enhancement
___
- Introduced enhanced column management in TUI settings, allowing users to toggle column visibility and reorder columns.
- Implemented key bindings for new column management features.
- Updated settings and table rendering to support dynamic column visibility and ordering.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>frontend.rs</strong><dd><code>Implement Column Visibility and Order Modification in TUI Settings</code></dd></summary>
<hr>
src/frontend.rs
<li>Added key bindings for toggling column visibility and moving columns <br>up and down in settings.<br>
</details>
</td>
<td><a …
=> feat(tui): allow modifying column visibility and order in settings

CHANGELOG.md
enhancement, documentation
___
- Updated `CHANGELOG.md` to include new features, improvements, and fixes for the upcoming 0.10.0 release.
- Notable additions include support for reordering and toggling column visibility in Tui, dublin ECMP routing for IPv6/udp, and a reduction in the maximum sequence per round.
- Adjusted the comparison links to reflect the latest version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Update CHANGELOG for Version 0.10.0 Release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
CHANGELOG.md
<li>Added entries for new …
=> Chore update changelog

.github/workflows/release.yml
See https://github.com/cross-rs/cross/issues/1447
___
enhancement
___
- Added `CROSS_NO_WARNINGS: 0` to the GitHub Actions release workflow to address the issue with cross fallback behavior as discussed in https://github.com/cross-rs/cross/issues/1447. This change ensures that warnings from the `cross` tool do not interfere with the build process.
___
<tr>
<td>
<details>
<summary><strong>release.yml</strong><dd><code>Add CROSS_NO_WARNINGS to GitHub Actions Release Workflow</code>&nbsp; </dd></summary>
<hr>
.github/workflows/release.yml
<li>Added <code>CROSS_NO_WARNINGS: 0</code> environment variable to the release <br>workflow to restore …
=> build: add `CROSS_NO_WARNINGS: 0` to restore prior cross fallback behaviour

CHANGELOG.md
documentation
___
- Added a new entry in the CHANGELOG.md to document the fix for a permission denied error when reading the configuration file from a snap installation.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Update CHANGELOG for Snap Installation Fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
CHANGELOG.md
<li>Added entry for fixing permission denied error when reading <br>configuration file from snap installation.<br>
</details>
</td>
<td><a href="https://github.com/fujiapple852/trippy/pull/1081/files#diff-06572a96a58dc510037d5efa622 …
=> chore: added #1058 to `CHANGELOG.md`

Cargo.lock, Cargo.toml, test_resources/config/completions_bash.txt
enhancement, configuration changes
___
- Updated project version to `0.11.0-dev` and MSRV to `1.75`.
- Removed version constraints for `clap` and `clap_complete`, updating their versions.
- Locked `serde_yaml` to `0.9.33` due to maintenance status.
- Improved Bash completion script compatibility by changing variable set checks.
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Project and Dependencies Version Update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
<li>Bumped project version to …
=> Bump version to 0.11.0 dev and update dependencies

CHANGELOG.md, README.md, src/config/columns.rs, src/frontend/columns.rs, src/frontend/render/table.rs, src/tracing/net/ipv4.rs, src/tracing/net/ipv6.rs, src/tracing/probe.rs, src/tracing/tracer.rs, trippy-config-sample.toml
=> feat: record icmp packet code (#734)

.github/dependabot.yml
- ignore patch update to all `serde*`, `clap*`, `anyhow` and `thiserror` crates
- include updates to transitive dependencies in `Cargo.lock` file
- disable auto rebasing of PRs
=> build: update dependabot configuration

crates/trippy-core/Cargo.toml, crates/trippy-dns/Cargo.toml, crates/trippy-packet/Cargo.toml, crates/trippy-privilege/Cargo.toml
Cargo will link to docs.rs instead
=> fix: remove documentation link from most crates

CHANGELOG.md, crates/trippy-packet/src/icmp_extension.rs
=> fix(core): tracer panic for ICMP extension with malformed length (#1287)

crates/trippy-core/src/state.rs
=> test(core): remove f64 comparison in `state` tests

crates/trippy-tui/locales/app.yml
=> Feat i18n fr

crates/trippy-tui/src/config.rs, crates/trippy-tui/src/frontend.rs, crates/trippy-tui/src/frontend/render/settings.rs, crates/trippy-tui/src/frontend/render/table.rs
Needed because kebab-case for `IP` is `i-p` but example toml file shows `ip`
so renamed to `Ip` so that kebab version is `ip`
Closes #1327
=> fix: rename IP to Ip

crates/trippy-tui/src/app.rs, crates/trippy-tui/src/geoip.rs, crates/trippy-tui/src/locale.rs
lookup the MaxMind `City` name in the current locale, with fallback to `en` if nothing is found.
Closes #1336
=> feat(geoip): lookup GeoIp with current locale (#1336)

CHANGELOG.md
#1319, #506, #1357, #1312, #1336, #1327 & #1289
=> doc: update CHANGELOG.md for 0.12.0 items

CHANGELOG.md, RELEASES.md, crates/trippy-tui/src/frontend/render/histogram.rs, crates/trippy-tui/src/frontend/render/history.rs
=> fix(tui): sample history and frequency charts ignore sub-millisecond samples

Cargo.lock, Cargo.toml, Dockerfile, crates/trippy-tui/Cargo.toml, crates/trippy-tui/build.rs, crates/trippy-tui/locales.toml, crates/trippy-tui/src/app.rs, crates/trippy-tui/src/frontend/render/bar.rs, crates/trippy-tui/src/frontend/render/settings.rs, crates/trippy-tui/src/lib.rs, crates/trippy-tui/src/locale.rs, crates/trippy-tui/src/print.rs
Alternative to #1426 for comparison. Strings are now `&'static str` as `phf::Map` entries, placeholder substitution is simply `str::replace`, no complex logic. Executable size is down 1MB (!).
Downsides are 1. build.rs, 2. `str::replace` is not enough for complex translations.
Currently both the `$kt:ident = $kt:expr` and `$kt:literal => $kv:expr` forms of `t!` are still supported, but I doubt if they really differ.
=> Replace rust-i18n with phf string maps and simple replaces

.github/workflows/ci.yml
Add a CI job to enforce conventional commits.
* Add a new job `conventional-commits` to `.github/workflows/ci.yml` to enforce conventional commits using `webiny/action-conventional-commits@v1`.
* Configure the job to run on every pull requests to the `master` branch.
* Define the conventional commit types: `feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `test`, `build`, and `ci`.
=> Add CI job to enforce conventional commits

crates/trippy-core/Cargo.toml, crates/trippy-core/src/state.rs, crates/trippy-core/tests/resources/state/non_default_minimum_ttl.toml
=> Fix core tracer panic fwd loss

.github/dependabot.yml
This reverts commit 56d2ff744daa2f5f50689bfeb8711a2643b9874a.
=> Revert "chore: disable dependabot for npm ecosystem"

deny.toml
see https://rustsec.org/advisories/RUSTSEC-2024-0436
=> chore: allow unmaintained `paste` crate

Cargo.lock, crates/trippy-tui/Cargo.toml, crates/trippy-tui/src/report/csv.rs, crates/trippy-tui/src/report/dot.rs, crates/trippy-tui/src/report/flows.rs, crates/trippy-tui/src/report/json.rs, crates/trippy-tui/src/report/silent.rs, crates/trippy-tui/src/report/stream.rs, crates/trippy-tui/src/report/table.rs, crates/trippy-tui/src/report/types.rs
=> Add report timestamps

crates/trippy-tui/src/config/file.rs, trippy-config-sample.toml
=> support reading config from `$XDG_CONFIG_HOME/trippy/trippy.toml`

crates/trippy-packet/src/icmpv4.rs, crates/trippy-packet/src/icmpv6.rs
=> fix(packet): overflow for `icmp[v4|v6]` packets of length >= 64 (#1561)
